/*
 * Credits
 * The Credits API provides information about customer credit lines.
 *
 * OpenAPI spec version: 2.2.0
 * Contact: gipinacho@santander.com.mx
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.bancosantander.likeu.model;

/**
 * Retrieves the assistance detail information
 */
public class AssistanceDetail {
	private String id = null;

	private java.util.Date operation_date;

	/**
 * Retrieves the assistance detail information
 */
	public AssistanceDetail() {
	}

/**
 * String
 * @param      id    array that is the source of characters.
 * @param      operation_date    array that is the source of characters.
 * @exception  IndexOutOfBoundsException  if the <code>offset</code>
 */
	public AssistanceDetail(java.lang.String id, java.util.Date operation_date) {
		this.id = id;
		this.operation_date = new java.util.Date(this.operation_date.getTime());
	}

	/**
	 * Indicates the status of the assistance. * &#x60;ACTIVE&#x60; - Indicates
	 * that status for recurrent payment is active in this moment. *
	 * &#x60;INACTIVE&#x60; - Indicates that the recurrent payment status is
	 * deactivated.
	 */
	public enum StatusEnum {
	/**
	 * @param String
   	 * @param String
	 */
		ACTIVE("ACTIVE"), INACTIVE("INACTIVE");

		private String value;

		/** 
	 * @param String
	 */
		StatusEnum(String value) {
			this.value = value;
		}
		/**
		 * @return
		 */		
		public String getValue() {
			return value;
		}

		@Override
		/**
		 * @return
		 */
		public String toString() {
			return String.valueOf(value);
		}


		/**
		 * Método que formatea un String
		 * @param   input  ingreso de String
		 * @return  retorno
		 */
		public static StatusEnum fromValue(String input) {
			for (StatusEnum b : StatusEnum.values()) {
				if (b.value.equals(input)) {
					return b;
				}
			}
			return null;
		}
	}

	private StatusEnum status = null;

	/**
	 * Indicates the assistance identifier.
	 * 
	 * @return id
	 **/
	public String getId() {
		return id;
	}
	/** 
	 * @param String
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * Indicates the status of the assistance. * &#x60;ACTIVE&#x60; - Indicates
	 * that status for recurrent payment is active in this moment. *
	 * &#x60;INACTIVE&#x60; - Indicates that the recurrent payment status is
	 * deactivated.
	 * 
	 * @return status
	 **/
	public StatusEnum getStatus() {
		return status;
	}
	/** 
	 * @param StatusEnum
	 */
	public void setStatus(StatusEnum status) {
		this.status = status;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class AssistanceDetail {\n");

		sb.append("    id: ").append(toIndentedString(id)).append("\n");
		sb.append("    status: ").append(toIndentedString(status)).append("\n");
		sb.append("    operation_date: ")
				.append(toIndentedString(operation_date)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}
	/**
    * Indicates the date on which the recurrent payment was made. [ISO 8601] (https://www.iso.org/iso-8601-date-and-time-format.html
    * @return operationDate
    **/
	public java.util.Date getOperation_date() {
		if (this.operation_date != null) {
			return new java.util.Date(this.operation_date.getTime());
		} else {
		return null;
		}
	}
	/** 
	 * @param Date
	 */
	public void setOperation_date(java.util.Date operation_date) {
		if (operation_date != null) {
			this.operation_date = new java.util.Date(operation_date.getTime());
		} else {
			this.operation_date = null;
		}
	}

}
