/*
 * Credits
 * The Credits API provides information about customer credit lines.
 *
 * OpenAPI spec version: 2.2.0
 * Contact: gipinacho@santander.com.mx
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.bancosantander.likeu.model;
/**
 * BenefitDetail
 */

public class BenefitDetail {

	private String type = null;

	private java.util.Date activation_date;

	private java.lang.String contract_key;

	private java.util.Date cut_of_date;

	private java.util.Date hiring_date;

	private java.util.Date last_evaluation_date;

		/**
 * BenefitDetail
 */
public BenefitDetail() {
}
/**
* String
* @param      type    array that is the source of characters.
* @param      activation_date    array that is the source of characters.
* @param      contract_key    array that is the source of characters.
* @param      cut_of_date    array that is the source of characters.
* @param      hiring_date    array that is the source of characters.
* @param      last_evaluation_date    array that is the source of characters.
* @param      card    array that is the source of characters.
* @exception  IndexOutOfBoundsException  if the <code>offset</code>
*/
public BenefitDetail(java.lang.String type, java.util.Date activation_date,
		java.lang.String contract_key, java.util.Date cut_of_date,
		java.util.Date hiring_date, java.util.Date last_evaluation_date,
		com.bancosantander.likeu.model.CardDetail card) {
	this.type = type;
	this.activation_date = new java.util.Date(activation_date.getTime());
	this.contract_key = contract_key;
	this.cut_of_date = new java.util.Date(cut_of_date.getTime());
	this.hiring_date = new java.util.Date(hiring_date.getTime());
	this.last_evaluation_date = new java.util.Date(last_evaluation_date.getTime());
	this.card = card;
}
	/**
	 * Indicates the status of the benefit. * &#x60;INITIAL&#x60; - Indicates
	 * the start of benefit. * &#x60;EVALUATION&#x60; - Indicates when the
	 * benefit is in Evaluation. * &#x60;FINAL&#x60; - Indicates the final phase
	 * of benefit.
	 */
	/**
	 * Adds 10 to the age
	 * 
	 * @param value
	 *            - The age to add 10 to
	 * @returns {value} - The age + 10
	 */
	public enum StatusEnum {
		/**
		 * @param String
		 * @param String
		 * @param String
		 */
		INITIAL("INITIAL"), EVALUATION("EVALUATION"), FINAL("FINAL");

		private String value;
		/**
		 * @param String
		 */
		StatusEnum(String value) {
			this.value = value;
		}

		/**
		 * Indicates the key contract for the benefit
		 * 
		 * @return value
		 **/
		public String getValue() {
			return value;
		}
	}

	private StatusEnum status = null;

	private CardDetail card = null;

	/**
	 * Indicates the benefit type
	 * 
	 * @return type
	 **/
	public String getType() {
		return type;
	}
	/**
	 * @param String
	 */
	public void setType(String type) {
		this.type = type;
	}

	/**
	 * Indicates the status of the benefit. * &#x60;INITIAL&#x60; - Indicates
	 * the start of benefit. * &#x60;EVALUATION&#x60; - Indicates when the
	 * benefit is in Evaluation. * &#x60;FINAL&#x60; - Indicates the final phase
	 * of benefit.
	 * 
	 * @return status
	 **/
	public StatusEnum getStatus() {
		return status;
	}
	/**
	 * @param StatusEnum
	 */
	public void setStatus(StatusEnum status) {
		this.status = status;
	}

	/**
	 * Get card
	 * 
	 * @return CardDetail
	 **/
	public CardDetail getCard() {
		return card;
	}
	/**
	 * @param CardDetail
	 */
	public void setCard(CardDetail card) {
		this.card = card;
	}

	public java.util.Date getActivation_date() {
		if (this.activation_date != null) {
			return new java.util.Date(this.activation_date.getTime());
		} else {
		return null;
		}
	}
	/** 
	 * @param Date
	 */
	public void setActivation_date(java.util.Date activation_date) {
		if (activation_date != null) {
			this.activation_date = new java.util.Date(activation_date.getTime());
		} else {
			this.activation_date = null;
		}
	}
	public java.lang.String getContract_key() {
		return this.contract_key;
	}
	/** 
	 * @param String
	 */
	public void setContract_key(java.lang.String contract_key) {
		this.contract_key = contract_key;
	}
	public java.util.Date getCut_of_date() {
		if (this.cut_of_date != null) {
			return new java.util.Date(this.cut_of_date.getTime());
		} else {
		return null;
		}
	}
	/** 
	 * @param Date
	 */
	public void setCut_of_date(java.util.Date cut_of_date) {
		if (cut_of_date != null) {
			this.cut_of_date = new java.util.Date(cut_of_date.getTime());
		} else {
			this.cut_of_date = null;
		}
	}
	public java.util.Date getHiring_date() {
		if (this.hiring_date != null) {
			return new java.util.Date(this.hiring_date.getTime());
		} else {
		return null;
		}
	}
	/** 
	 * @param Date
	 */
	public void setHiring_date(java.util.Date hiring_date) {
		if (hiring_date != null) {
			this.hiring_date = new java.util.Date(hiring_date.getTime());
		} else {
			this.hiring_date = null;
		}
	}
	public java.util.Date getLast_evaluation_date() {
		if (this.last_evaluation_date != null) {
			return new java.util.Date(this.last_evaluation_date.getTime());
		} else {
		return null;
		}
	}
	/** 
	 * @param Date
	 */
	public void setLast_evaluation_date(java.util.Date last_evaluation_date) {
		if (last_evaluation_date != null) {
			this.last_evaluation_date = new java.util.Date(last_evaluation_date.getTime());
		} else {
			this.last_evaluation_date = null;
		}
	}

}
