/*
 * Credits
 * The Credits API provides information about customer credit lines.
 *
 * OpenAPI spec version: 2.2.0
 * Contact: gipinacho@santander.com.mx
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.bancosantander.likeu.model;

import java.util.Objects;

/**
 * Retrieves the domiciliation status detail information
 */
public class DomiciliationDetail {

	private String id = null;

	private java.util.Date operation_date;

	/**
	 * Retrieves the domiciliation status detail information
	 */
	public DomiciliationDetail() {
	}
	/**
	 * Constructor de la clase
	 * @param      id    iodentificador.
	 * @param      operation_date    fecha operación.
	 * @exception  IndexOutOfBoundsException  if the <code>offset</code>
	 */
	public DomiciliationDetail(java.lang.String id,
			java.util.Date operation_date) {
		this.id = id;
		this.operation_date =  new java.util.Date(this.operation_date.getTime());
	}

	/**
	 * Indicates the status of the domiciliation. * &#x60;ACTIVE&#x60; -
	 * Indicates that status for domiciliation is active in this moment. *
	 * &#x60;INACTIVE&#x60; - Indicates that the domiciliation status is
	 * inactive.
	 */
	public enum StatusEnum {
		/**
		 * @param String
		 * @param String
		*/		
		ACTIVE("ACTIVE"), INACTIVE("INACTIVE");

		private String value;
		/** 
		 * @param String
		 */
		StatusEnum(String value) {
			this.value = value;
		}
		/**
		 * Indicates the key contract for the benefit
		 * 
		 * @return value
		 **/
		public String getValue() {
			return value;
		}

		@Override
		/** 
		 * @param String
		 */
		public String toString() {
			return String.valueOf(value);
		}
		/** 
		 * @param String
		 * @return
		 */
		public static StatusEnum fromValue(String input) {
			for (StatusEnum b : StatusEnum.values()) {
				if (b.value.equals(input)) {
					return b;
				}
			}
			return null;
		}

	}

	private StatusEnum status = null;

	/**
	 * Indicates the domiciliation identifier.
	 * 
	 * @return id
	 **/
	public String getId() {
		return id;
	}
	/** 
	 * @param String
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * Indicates the status of the domiciliation. * &#x60;ACTIVE&#x60; -
	 * Indicates that status for domiciliation is active in this moment. *
	 * &#x60;INACTIVE&#x60; - Indicates that the domiciliation status is
	 * inactive.
	 * 
	 * @return status
	 **/
	public StatusEnum getStatus() {
		return status;
	}
	/** 
	 * @param StatusEnum
	 */
	public void setStatus(StatusEnum status) {
		this.status = status;
	}

	@Override
	/** 
	 * @return
	 */
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class DomiciliationDetail {\n");

		sb.append("    id: ").append(toIndentedString(id)).append("\n");
		sb.append("    status: ").append(toIndentedString(status)).append("\n");
		sb.append("    operation_date: ")
				.append(toIndentedString(operation_date)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 * @param o
	 * @return
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}
	/**
	 * @return
	 */	
	public java.util.Date getOperation_date() {
		if (this.operation_date != null) {
			return new java.util.Date(this.operation_date.getTime());
		} else {
		return null;
		}
	}
	/** 
	 * @param Date
	 */
	public void setOperation_date(java.util.Date operation_date) {
		if (operation_date != null) {
			this.operation_date = new java.util.Date(operation_date.getTime());
		} else {
			this.operation_date = null;
		}
	}

}