/*
 * Credits
 * The Credits API provides information about customer credit lines.
 *
 * OpenAPI spec version: 2.2.0
 * Contact: gipinacho@santander.com.mx
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.bancosantander.likeu.model;

import java.math.BigDecimal;

/**
 * Money Fields that represent money, must follow this structure:
 */

public class Money {
	private BigDecimal amount = null;

	private java.lang.String currency_code;
/**
 * Money Fields that represent money, must follow this structure:
 */
	public Money() {
	}
/**
	 * Constructor de la clase
	 * @param      amount    iodentificador.
	 * @return     retorno del metodo
	 * @exception  IndexOutOfBoundsException  if the <code>offset</code>
	 */
	public Money amount(BigDecimal amount) {
		this.amount = amount;
		return this;
	}
	/**
	 * Constructor de la clase
	 * @param      amount    iodentificador.
	 * @param      currency_code    fecha operación.
	 * @exception  IndexOutOfBoundsException  if the <code>offset</code>
	 */
	public Money(java.math.BigDecimal amount, java.lang.String currency_code) {
		this.amount = amount;
		this.currency_code = currency_code;
	}
	/**
	 * Amount - number
	 * 
	 * @return amount
	 **/
	public BigDecimal getAmount() {
		return amount;
	}
	/** 
	 * @param BigDecimal
	 */
	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}
	/** 
	 * Money
	 * @param currency_code  moneda
	 * @return retorno del metodo
	 */
	public Money currency_code(String currency_code) {
		this.currency_code = currency_code;
		return this;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class Money {\n");

		sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
		sb.append("    currency_code: ")
				.append(toIndentedString(currency_code)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 * @param      0    iodentificador.
	 * @exception  IndexOutOfBoundsException  if the <code>offset</code>
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}


	/** 
	 * @retunr
	 */
	public java.lang.String getCurrency_code() {
		return this.currency_code;
	}
	/** 
	 * @param String
	 */
	public void setCurrency_code(java.lang.String currency_code) {
		this.currency_code = currency_code;
	}
}