/*
 * Credits
 * The Credits API provides information about customer credit lines.
 *
 * OpenAPI spec version: 2.2.0
 * Contact: gipinacho@santander.com.mx
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.bancosantander.likeu.model;

/**
 * Retrieves the payment card basic information
 */
public class PaymentDetail {
	private java.lang.Integer amount_payment;

	private java.lang.Integer minimum_amount;

	private java.util.Date operation_date;

	/**
	 * Retrieves the period basic information
	 */
	public PaymentDetail() {
	}

/**
 * String
 * @param      amount_payment    array that is the source of characters.
 * @param      minimum_amount    array that is the source of characters.
 * @param      operation_date    array that is the source of characters.
 * @exception  IndexOutOfBoundsException  if the <code>offset</code>
 */
	public PaymentDetail(java.lang.Integer amount_payment,
			java.lang.Integer minimum_amount, java.util.Date operation_date) {
		this.amount_payment = amount_payment;
		this.minimum_amount = minimum_amount;
		this.operation_date = new java.util.Date(operation_date.getTime());
	}

	@Override
	/** 
	 * @return
	 */
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class PaymentDetail {\n");

		sb.append("    amount_payment: ")
				.append(toIndentedString(amount_payment)).append("\n");
		sb.append("    minimum_amount: ")
				.append(toIndentedString(minimum_amount)).append("\n");
		sb.append("    operation_date: ")
				.append(toIndentedString(operation_date)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 * @param o
	 * @return
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}
	/**
    * Indicates the amount
    * @return
    **/
	public java.lang.Integer getAmount_payment() {
		return this.amount_payment;
	}
	/** 
	 * @param Integer
	 */
	public void setAmount_payment(java.lang.Integer amount_payment) {
		this.amount_payment = amount_payment;
	}
	/**
    * Indicates the minimum
    * @return 
    **/
	public java.lang.Integer getMinimum_amount() {
		return this.minimum_amount;
	}
	/** 
	 * @param Integer
	 */
	public void setMinimum_amount(java.lang.Integer minimum_amount) {
		this.minimum_amount = minimum_amount;
	}
	/**
    * Indicates the date on which the recurrent payment was made. [ISO 8601] (https://www.iso.org/iso-8601-date-and-time-format.html
    * @return operationDate
    **/
	public java.util.Date getOperation_date() {
		if (this.operation_date != null) {
			return new java.util.Date(this.operation_date.getTime());
		} else {
		return null;
		}
	}
	/** 
	 * @param Date
	 */
	public void setOperation_date(java.util.Date operation_date) {
		if (operation_date != null) {
			this.operation_date = new java.util.Date(operation_date.getTime());
		} else {
			this.operation_date = null;
		}
	}

}
