/*
 * Credits
 * The Credits API provides information about customer credit lines.
 *
 * OpenAPI spec version: 2.2.0
 * Contact: gipinacho@santander.com.mx
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.bancosantander.likeu.model;

import java.util.Objects;

/**
 * Retrieves the payroll portability detail information for this period
 */
public class PayrollDetail {
	private String id = null;

	private java.util.Date operation_date;
/**
 * Retrieves the payroll portability detail information for this period
 */
	public PayrollDetail() {
	}
/**
 * String
 * @param      id    array that is the source of characters.
 * @param      operation_date    array that is the source of characters.
 * @exception  IndexOutOfBoundsException  if the <code>offset</code>
 */
	public PayrollDetail(java.lang.String id, java.util.Date operation_date) {
		this.id = id;
		this.operation_date = new java.util.Date(this.operation_date.getTime());
	}

	/**
	 * Indicates the status of the payroll portability. * &#x60;ACTIVE&#x60; -
	 * Indicates that status for payroll portability is active in this moment. *
	 * &#x60;INACTIVE&#x60; - Indicates that the payroll portability status is
	 * deactivated.
	 */
	public enum StatusEnum {
		/**
		 * @param String
		 * @param String
		 */
		ACTIVE("ACTIVE"), INACTIVE("INACTIVE");

		private String value;
		/**
		 * @param String
		 */
		StatusEnum(String value) {
			this.value = value;
		}
		/**
		 * Indicates the key contract for the benefit
		 * 
		 * @return value
		 **/
		public String getValue() {
			return value;
		}

	}

	private StatusEnum status = null;

	/**
	 * Indicates the payroll portability identifier.
	 * 
	 * @return id
	 **/
	public String getId() {
		return id;
	}
	/**
	 * @param String
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * Indicates the status of the payroll portability. * &#x60;ACTIVE&#x60; -
	 * Indicates that status for payroll portability is active in this moment. *
	 * &#x60;INACTIVE&#x60; - Indicates that the payroll portability status is
	 * deactivated.
	 * 
	 * @return status
	 **/
	public StatusEnum getStatus() {
		return status;
	}
	/**
	 * @param StatusEnum
	 */
	public void setStatus(StatusEnum status) {
		this.status = status;
	}

	public java.util.Date getOperation_date() {
		if (this.operation_date != null) {
			return new java.util.Date(this.operation_date.getTime());
		} else {
			return null;
		}
	}
	public void setOperation_date(java.util.Date operation_date) {
		if (operation_date != null) {
			this.operation_date = new java.util.Date(operation_date.getTime());
		} else {
			this.operation_date = null;
		}
	}
}
