/*
 * Credits
 * The Credits API provides information about customer credit lines.
 *
 * OpenAPI spec version: 2.2.0
 * Contact: gipinacho@santander.com.mx
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.bancosantander.likeu.model;

import java.util.Objects;
import java.util.List;

/**
 * PeriodInfo
 */

public class PeriodInfo {

	private java.lang.Integer current_period;

	private java.util.List<com.bancosantander.likeu.model.PeriodDetail> period_detail;
/**
 * PeriodInfo
 */	
	public PeriodInfo() {
	}
/**
 * String
 * @param      current_period    array that is the source of characters.
 * @param      period_detail    array that is the source of characters.
 * @exception  IndexOutOfBoundsException  if the <code>offset</code>
 */
	public PeriodInfo(
			java.lang.Integer current_period,
			java.util.List<com.bancosantander.likeu.model.PeriodDetail> period_detail) {
		this.current_period = current_period;
		this.period_detail = period_detail;
	}
	/**
	 * Indicates the status of the period. * &#x60;ACTIVE&#x60; - Indicates that
	 * status for period is active in this moment. * &#x60;INACTIVE&#x60; -
	 * Indicates that the period is inactive.
	 */
	public enum StatusEnum {
		/**
		 * @param String
		 * @param String
		*/
		ACTIVE("ACTIVE"), INACTIVE("INACTIVE");

		private String value;

		/**
		 * @param String
		 */
		StatusEnum(String value) {
			this.value = value;
		}
		/**
		 * Indicates the key contract for the benefit
		 * 
		 * @return value
		 **/
		public String getValue() {
			return value;
		}

		@Override
		/**
		 * Indicates the key contract for the benefit
		 * 
		 * @return value
		 **/
		public String toString() {
			return String.valueOf(value);
		}
		/**
 * String
 * @param      input    array that is the source of characters.
 * @return   retorno
 */
		public static StatusEnum fromValue(String input) {
			for (StatusEnum b : StatusEnum.values()) {
				if (b.value.equals(input)) {
					return b;
				}
			}
			return null;
		}
	}
	private StatusEnum status = null;

	/**
	 * Indicates the status of the period. * &#x60;ACTIVE&#x60; - Indicates that
	 * status for period is active in this moment. * &#x60;INACTIVE&#x60; -
	 * Indicates that the period is inactive.
	 * 
	 * @return status
	 **/
	public StatusEnum getStatus() {
		return status;
	}

	/**
	 * @param StatusEnum
	 */
	public void setStatus(StatusEnum status) {
		this.status = status;
	}

	@Override
	/**
	 * @return
	 */
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class PeriodInfo {\n");

		sb.append("    current_period: ")
				.append(toIndentedString(current_period)).append("\n");
		sb.append("    status: ").append(toIndentedString(status)).append("\n");
		sb.append("    period_detail: ").append(toIndentedString(period_detail))
				.append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	/**
	 * @param o
	 * @return
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

	/**
	 * @return
	 */
	public java.lang.Integer getCurrent_period() {
		return this.current_period;
	}

	/**
	 * @param Integer
	 */
	public void setCurrent_period(java.lang.Integer current_period) {
		this.current_period = current_period;
	}
	/**
	 * @return
	 */
	public java.util.List<com.bancosantander.likeu.model.PeriodDetail> getPeriod_detail() {
		return this.period_detail;
	}

	/**
	 * @param List
	 */
	public void setPeriod_detail(
			java.util.List<com.bancosantander.likeu.model.PeriodDetail> period_detail) {
		this.period_detail = period_detail;
	}
}
