/*
 * Credits
 * The Credits API provides information about customer credit lines.
 *
 * OpenAPI spec version: 2.2.0
 * Contact: gipinacho@santander.com.mx
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.bancosantander.likeu.model;

import java.util.Objects;

/**
 * Retrieves the recurrent payment detail information
 */
public class RecurrentPaymentDetail {
	private String id = null;

	private java.util.Date operation_date;
/**
 * Retrieves the recurrent payment detail information
 */
	public RecurrentPaymentDetail() {
	}
/**
 * String
 * @param      id    array that is the source of characters.
 * @param      operation_date    array that is the source of characters.
 * @param      operationDate    array that is the source of characters.
 * @exception  IndexOutOfBoundsException  if the <code>offset</code>
 */
	public RecurrentPaymentDetail(java.lang.String id,
			java.util.Date operation_date, java.util.Date operationDate) {
		this.id = id;
		this.operation_date = new java.util.Date(operation_date.getTime());
		this.operationDate = new java.util.Date(operationDate.getTime());
	}

	/**
	 * Indicates the status of the recurrent payment. * &#x60;ACTIVE&#x60; -
	 * Indicates that status for recurrent payment is active in this moment. *
	 * &#x60;INACTIVE&#x60; - Indicates that the recurrent payment status is
	 * inactive.
	 */
	public enum StatusEnum {
		/**
		 * @param String
		 * @param String
		*/
		ACTIVE("ACTIVE"), INACTIVE("INACTIVE");

		private String value;

		/**
		 * @param String
		 */
		StatusEnum(String value) {
			this.value = value;
		}
		/**
		 * Indicates the key contract for the benefit
		 * 
		 * @return value
		 **/
		public String getValue() {
			return value;
		}

		@Override
		/**
		 * Indicates the key contract for the benefit
		 * 
		 * @return value
		 **/
		public String toString() {
			return String.valueOf(value);
		}
		/**
		 * String
		 * @param      input    array that is the source of characters.
		 * @return   retorno
		 */
		public static StatusEnum fromValue(String input) {
			for (StatusEnum b : StatusEnum.values()) {
				if (b.value.equals(input)) {
					return b;
				}
			}
			return null;
		}
	}

	private StatusEnum status = null;

	private java.util.Date operationDate = null;

	/**
	 * Indicates the reccurrent payment identifier.
	 * 
	 * @return id
	 **/
	public String getId() {
		return id;
	}

	/**
	 * @param String
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * Indicates the status of the recurrent payment. * &#x60;ACTIVE&#x60; -
	 * Indicates that status for recurrent payment is active in this moment. *
	 * &#x60;INACTIVE&#x60; - Indicates that the recurrent payment status is
	 * inactive.
	 * 
	 * @return status
	 **/
	public StatusEnum getStatus() {
		return status;
	}
	/**
	 * @param StatusEnum
	 */
	public void setStatus(StatusEnum status) {
		this.status = status;
	}

	/**
	 * Indicates the date on which the recurrent payment was made. [ISO 8601]
	 * (https://www.iso.org/iso-8601-date-and-time-format.html
	 * 
	 * @return operationDate
	 **/
	public java.util.Date getOperationDate() {
		if (this.operationDate != null) {
			return new java.util.Date(this.operationDate.getTime());
		} else {
		return null;
		}
	}
	/**
	 * @param Date
	 */
	public void setOperationDate(java.util.Date operationDate) {
		if (operationDate != null) {
			this.operationDate = new java.util.Date(operationDate.getTime());
		} else {
			this.operationDate = null;
		}
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class RecurrentPaymentDetail {\n");

		sb.append("    id: ").append(toIndentedString(id)).append("\n");
		sb.append("    status: ").append(toIndentedString(status)).append("\n");
		sb.append("    operationDate: ")
				.append(toIndentedString(operationDate)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 * @return
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}
	/**
	 * @return
	 */
	public java.util.Date getOperation_date() {
		if (this.operation_date != null) {
			return new java.util.Date(this.operation_date.getTime());
		} else {
		return null;
		}
	}
	/**
	 * @param Date
	 */
	public void setOperation_date(java.util.Date operation_date) {
		if (operation_date != null) {
			this.operation_date = new java.util.Date(operation_date.getTime());
		} else {
			this.operation_date = null;
		}
	}
}
